### ISSUE TITLE
Locally hosting Github Pages

### ISSUE THREAD

**Issue by Sethegrossman** [deargle-classes/msbx5500-spring-2020#7]
**Which lab are you even talking about**
Lab1

**Which part of that lab**
Hosting a Github Page

**Why is it confusing**
I am getting errors in my command line, and searching for youtube videos / googling has not been helpful
If relevant:
* **What did you try**
I cloned my repository onto my desktop, then ran:
bundle exec jekyll serve
* **What did you expect to happen**
It would serve the website
* **What happened instead**
this error:
Bundler could not find compatible versions for gem "bundler":

**Screenshots**
![image](https://user-images.githubusercontent.com/56364656/73985829-6febc380-48f9-11ea-9633-1fb4009e789c.png)

**Additional context**
After getting the error, I check my ruby installation and reinstalled bundler, but it was to no avail

**Comment by deargle** [comment]
The problem is that your default bundler is _too new_ for the one that github pages requires. You'll need to (1) install an old version of bundler, and (2) specify it for the first run of bundler. (You forgot to run `bundle install` anyway).

https://makandracards.com/makandra/9741-run-specific-version-of-bundler see section "You can solve this with." Do both of those things, except using the version of bundler that the error message asks for. After you run `bundle install` using that version, you'll be able to run `bundle exec jekyll serve` without specifying the older version.

**Comment by deargle** [comment]
Also, the word `localhost` refers to a host -- it is not a verb. You are asking about "locally hosting" your github pages site. You may rename this issue to practice proper vocabulary.

**Comment by deargle** [comment]
Also also, cool kids use WSL ubuntu instead of installing things into windows, but nevermind that for now.

**Comment by deargle** [comment]
Also also also, I found the above link by google-searching "bundler use old version", which I decided to google after carefully reading the error message when I had the same problem as you.

**Comment by Sethegrossman** [comment]
Okay, so run 
gem install bundler -v 1.0.10
bundle _1.0.10_ install
then how do I call: `"bundle exec jekyll serve" with the older version?

**Comment by deargle** [comment]
Reread my first post, that version is too old,  you need to get and use a
version of bundler compatible with the one the error message says you need.
Also, once you have run bundle install using a compatible version, then any
subsequent calls to bundler from that directory will use the version you
specified when you ran bundle install.

Also, on github, it will render posts as markdown unless you couch with
backticks. That's why your post has italics.

**Comment by Sethegrossman** [comment]
Okay got past that part, do you know anything about mapping values?
![image](https://user-images.githubusercontent.com/56364656/73987604-29e52e80-48fe-11ea-8474-2b6e27bcb9c9.png)

**Comment by deargle** [comment]
That's a YAML parsing error, error in your _config.yml

**Comment by deargle** [comment]
Did you figure it out? Error message suggests that line 4 is the culprit

**Comment by Sethegrossman** [comment]
Yes, I got it to work, but the template I was trying to use wanted me to do a lot of things I didn't understand in order to make it work properly. Rather than spending a couple hours on it. I am switching to a new one and am going to see if I can get it up and running.
